- name: Build API Docker image
  community.docker.docker_image_build:
    name: "{{ docker_api_image }}"
    path: /Users/michal/Dev/mgr
    dockerfile: Dockerfile

- name: Push API Docker image to remote repository
  community.docker.docker_image_push:
    name: "{{ docker_api_image }}"
