
services:
  api:
    image: taskmgr:latest
    ports:
      - "8080:8080"
    volumes:
      - /Users/michal/Dev/mgr/src/api:/app
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
    volumes:
      - /Users/michal/Dev/mgr/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
