
services:
  taskmgr-api:
    image: taskmgr:latest
    ports:
      - "8080:8080"
    volumes:
      - ./src/api:/app
    depends_on:
      - taskmgr-mysql

  taskmgr-mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: task_manager
    #   MYSQL_USER: user
    #   MYSQL_PASSWORD: password
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./scripts/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro

    # entrypoint: ["/usr/local/bin/entrypoint.sh"]

