# ============================================================================== #
# header
# ============================================================================== #
---
- name: Create project directory
  ansible.builtin.file:
    path: "{{ compose_project_source_path }}"
    state: directory

- name: Render docker-compose template
  ansible.builtin.template:
    src: "{{ compose_template_path }}"
    dest: "{{ compose_rendered_template_path }}"
  register: output

- name: Run docker compose up
  community.docker.docker_compose_v2:
    project_src: "{{ compose_project_source_path }}"
    project_name: "{{ project_name }}"
    build: always
