
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
    volumes:
      - /Users/michal/Dev/mgr/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  api:
    image: taskmgr:latest
    ports:
      - "5050:5050"
    volumes:
      - /Users/michal/Dev/mgr/src/api:/app
    depends_on:
      - mysql

  webserver:
    image: nginx
    ports:
    - "8080:80"
    volumes:
    - /Users/michal/Dev/mgr/src/frontend:/usr/share/nginx/html:ro
    - /Users/michal/Dev/mgr/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
