# ============================================================================= #
# header
# ============================================================================== #
---
- name: Stop all services
  community.docker.docker_compose_v2:
    project_src: "{{ compose_project_source_path }}"
    project_name: "{{ project_name }}"
    state: stopped

- name: Delete docker-compose file
  ansible.builtin.file:
    path: "{{ compose_rendered_template_path }}"
    state: absent

- name: Delete project directory
  ansible.builtin.file:
    path: "{{ compose_project_source_path }}"
    state: absent
