apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: api
        image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
        ports:
        - containerPort: {{ .Values.api.service.port }}
        env:
        - name: DATABASE_URL
          value: "mysql://{{ .Values.mysql.user }}:{{ .Values.mysql.password }}@mysql-service:3306/{{ .Values.mysql.database }}"
