apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image }}:{{ .Values.mysql.tag }}"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.mysql.rootPassword }}"
        - name: MYSQL_DATABASE
          value: "{{ .Values.mysql.database }}"
        - name: MYSQL_USER
          value: "{{ .Values.mysql.user }}"
        - name: MYSQL_PASSWORD
          value: "{{ .Values.mysql.password }}"
        ports:
        - containerPort: {{ .Values.mysql.service.port }}
