apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: {{ .Values.mysql.service.port }}
    targetPort: 3306
  type: ClusterIP
